<a href="https://colab.research.google.com/github/kra2839/2024-intro-DA-code/blob/main/4%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.arange(6). reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b= np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
c=np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [ ]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [ ]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [ ]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [ ]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [ ]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [ ]:
d=np.array([100,200,300])
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
import numpy as np

a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
c=np.array([[10,20],[30,40]])
c

array([[10, 20],
       [30, 40]])

In [ ]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
import numpy as np

x=np.array([1,2,3])
y=np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
import numpy as np

a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [ ]:
c=np.array([[10,20][30,40]])
c

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-27-ced8e3a848b7>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  c=np.array([[10,20][30,40]])


TypeError: list indices must be integers or slices, not tuple

In [ ]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
np.hstack((np.arange(3),np.arange(10,15)))


array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [ ]:
import numpy as np

a= np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
b=np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [ ]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [ ]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
y[:,np.newaxis]

array([[10],
       [20],
       [30]])

In [ ]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [ ]:
np.hstack((x,y))
np.column_stack==np.hstack

False

In [ ]:
import numpy as np

a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b=np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [ ]:
a=np.array([4.,2.,1.])
b=np.array([3.,8.,7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [ ]:
np.row_stack==np.vstack

True

In [ ]:
import numpy as np

a= np.array([1,2])
b= np.array([3,4])
c= np.array([5,6])

In [ ]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b,c),axis=None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z=np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [ ]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
np.concatenate((x,y),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [ ]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [ ]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [ ]:
import numpy as ap

a= np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b= np.array([4,5,6])
b

array([4, 5, 6])

In [ ]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.stack((a,b),axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
z=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
ax0=np.stack((x,y,z),axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [ ]:
ax0.shape

(3, 2, 3)

In [ ]:
ax2=np.stack((x,y,z),axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
ax0.shape

(3, 2, 3)

In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
np.expand_dims(x,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [ ]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [ ]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [ ]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [ ]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [ ]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [ ]:
import numpy as np

a= np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c=np.arange(1,6,2)
c

array([1, 3, 5])

In [ ]:
np.hstack((a,c[:,np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.hstack((a,c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
np.hstack((a,np.expand_dims(c,axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a,c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
import numpy as np

a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b=np.arange(1,5)
b

array([1, 2, 3, 4])

In [ ]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
np.vstack((a,b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])


In [ ]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x=np.array([[1,2,3]])
y=np.array([[4,5,6]])

In [ ]:
np.c_[x,y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.column_stack((x,y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x,10,20,y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack[x,10,20,y]

TypeError: 'numpy._ArrayFunctionDispatcher' object is not subscriptable

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a,0,0,b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [ ]:
np.r_[3:10:3,[0]*2,5,6]

array([3, 6, 9, 0, 0, 5, 6])

In [ ]:
np.r_[-1:1:6j,[0]*2,5,6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [ ]:
np.linspace(-1,1,6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [ ]:
a=np.array([[0,1,2],[3,4,5])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [ ]:
np.r_[a,a,a]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.r_['0',a,a]

array([1, 2, 3, 1, 2, 3])

In [ ]:
np.r_['-1',a,a]

array([1, 2, 3, 1, 2, 3])

In [ ]:
np.r_['1',a,a]

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.r_['0,2',[1,2,3],[4,5,6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_['0,3',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0,3,0',[1,2,3],[4,5,6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [ ]:
np.r_['0,3,0',[1,2,3],[4,5,6]].shape

(6, 1, 1)

In [ ]:
np.r_['0,3,2',[1,2,3],[4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [ ]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.row_stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.r_[a[np.newaxis, :], b[np.newaxis,:]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [ ]:
np.column_stack((a,b))


array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.concatenate(((a[:,np.newaxis], b[:,np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
import numpy as np

x=np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [5]:
s=np.split(x,3)
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [6]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


In [ ]:
np.split(x,4)

ValueError: array split does not result in an equal division

In [7]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.split(x, [2, 6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [9]:
x=np.split(x,[2,6])

[array([1,2]),array([3,4,5,6]),array([7,8,9])]

NameError: name 'array' is not defined

In [10]:
y=np.arange(10,61,10)
y

array([10, 20, 30, 40, 50, 60])

In [11]:
np.split(y,[2,3,4])

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [12]:
np.split(y,[2,3,4,6])

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [13]:
y[4:6]

array([50, 60])

In [14]:
y[6:]

array([], dtype=int64)

In [15]:
a=np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
np.split(a,3,axis=1)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [19]:
np,split(a,4,axis=1)

NameError: name 'split' is not defined

In [20]:
np.split(a,[3,5,7],axis=1)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [21]:
b=np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
np.split(b,3,axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [23]:
np.split(b,[2,4,6],axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

In [24]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [26]:
np.hsplit(a,[2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [28]:
a=np.arange(24).reshape(2,12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [29]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [30]:
np.hsplit(a,4)

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [31]:
a[:,:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [32]:
a[:,8:]

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [33]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a=np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [35]:
np.vsplit(a,3)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [36]:
a[:1,:]

array([[0, 1, 2]])

In [37]:
a[4:6,:]

array([[12, 13, 14],
       [15, 16, 17]])

In [38]:
import numpy as np

x=np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [39]:
np.array_split(x,2)

[array([0., 1., 2., 3., 4.]), array([5., 6., 7., 8.])]

In [40]:
np.array_split(x,3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [41]:
np.array_split(x,4)

[array([0., 1., 2.]), array([3., 4.]), array([5., 6.]), array([7., 8.])]

In [42]:
np.array_split(x,5)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8.])]

In [43]:
np.array_split(x,[2,4,6])

[array([0., 1.]), array([2., 3.]), array([4., 5.]), array([6., 7., 8.])]

In [44]:
import numpy as np

a=np.arange(35).reshape(7,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [45]:
np.array_split(a,2,axis=0)

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [46]:
np.array_split(a,2,axis=1)

[array([[ 0,  1,  2],
        [ 5,  6,  7],
        [10, 11, 12],
        [15, 16, 17],
        [20, 21, 22],
        [25, 26, 27],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24],
        [28, 29],
        [33, 34]])]

In [47]:
np.array_split(a,4,axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [48]:
np.array_split(a,4,axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [18],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [50]:
np.array_split(a,[2,4],axis=0)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]])]

In [51]:
np.array_split(a,[2,4],axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21],
        [25, 26],
        [30, 31]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23],
        [27, 28],
        [32, 33]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24],
        [29],
        [34]])]

In [53]:
np.split(x,[2,4,5],axis=2)

IndexError: tuple index out of range

In [54]:
x[:,:,5:]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [56]:
import numpy as np

x=np.arange(24).reshape(2,2,6)
x

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [57]:
np.dsplit(x,2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [58]:
np.split(x,2,axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [59]:
np.split(x,2,axis=2)

[array([[[ 0,  1,  2],
         [ 6,  7,  8]],
 
        [[12, 13, 14],
         [18, 19, 20]]]),
 array([[[ 3,  4,  5],
         [ 9, 10, 11]],
 
        [[15, 16, 17],
         [21, 22, 23]]])]

In [60]:
np.dsplit(x,3)

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]

In [61]:
np.dsplit(x,[2,4,5])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]),
 array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]),
 array([[[ 4],
         [10]],
 
        [[16],
         [22]]]),
 array([[[ 5],
         [11]],
 
        [[17],
         [23]]])]

In [62]:
x[:,:,4:5]

array([[[ 4],
        [10]],

       [[16],
        [22]]])