<a href="https://colab.research.google.com/github/kra2839/2024-intro-DA-code/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%9E%85%EB%AC%B8%204%EC%9E%A5%203%EC%A0%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x7B31E9465D20

In [2]:
# Generate one random float uniformly distributed over the range[0,1)
r=rg.random()
r

0.22733602246716966

In [4]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [5]:
rg.random((4,3))

array([[0.59830875, 0.18673419, 0.67275604],
       [0.94180287, 0.24824571, 0.94888115],
       [0.66723745, 0.09589794, 0.44183967],
       [0.88647992, 0.6974535 , 0.32647286]])

In [8]:
import numpy as np

rg = np.random.default_rng(12345)
r= rg.integers(low=0,high=10,size=3)
r

array([6, 2, 7])

In [9]:
rg.integers(1,7,(3,4))

array([[2, 2, 5, 4],
       [5, 6, 3, 6],
       [2, 4, 4, 2]])

In [10]:
import numpy as np

rg= np.random.default_rng(seed=42)
rg.standard_normal((4,3))

array([[ 0.30471708, -1.03998411,  0.7504512 ],
       [ 0.94056472, -1.95103519, -1.30217951],
       [ 0.1278404 , -0.31624259, -0.01680116],
       [-0.85304393,  0.87939797,  0.77779194]])