<a href="https://colab.research.google.com/github/kra2839/2024-intro-DA-code/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%EC%9E%85%EB%AC%B8%204%EC%9E%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = np.arange(6). reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b= np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
c=np.arange(20,24).reshape(2,2)
c

array([[20, 21],
       [22, 23]])

In [9]:
np.vstack((a,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [10]:
np.vstack((a,b,c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [11]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [12]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [14]:
d=np.array([100,200])
np.vstack((a,d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [15]:
d=np.array([100,200,300])
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [16]:
import numpy as np

a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [18]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [20]:
c=np.array([[10,20],[30,40]])
c

array([[10, 20],
       [30, 40]])

In [21]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [22]:
import numpy as np

x=np.array([1,2,3])
y=np.array([5,6,7])
np.vstack((x,y))

array([[1, 2, 3],
       [5, 6, 7]])

In [24]:
import numpy as np

a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [26]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [27]:
c=np.array([[10,20][30,40]])
c

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-27-ced8e3a848b7>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  c=np.array([[10,20][30,40]])


TypeError: list indices must be integers or slices, not tuple

In [28]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [29]:
np.hstack((a,c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [30]:
np.hstack((np.arange(3),np.arange(10,15)))


array([ 0,  1,  2, 10, 11, 12, 13, 14])

In [31]:
import numpy as np

a= np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [33]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [34]:
b=np.arange(10,22).reshape(3,4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [36]:
np.column_stack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [37]:
np.hstack((a,b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [38]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x,y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [39]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [40]:
y[:,np.newaxis]

array([[10],
       [20],
       [30]])

In [41]:
x=np.array([1,2,3])
y=np.array([10,20,30])
np.column_stack((x[:,np.newaxis],y[:,np.newaxis]))


array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [42]:
np.hstack((x,y))
np.column_stack==np.hstack

False

In [43]:
import numpy as np

a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
b=np.arange(10,22).reshape(4,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [45]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [46]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [47]:
a=np.array([4.,2.,1.])
b=np.array([3.,8.,7.])
print(np.row_stack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [48]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [49]:
print(np.vstack((a,b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [50]:
np.row_stack==np.vstack

True

In [51]:
import numpy as np

a= np.array([1,2])
b= np.array([3,4])
c= np.array([5,6])

In [52]:
np.concatenate((a,b,c))

array([1, 2, 3, 4, 5, 6])

In [53]:
np.concatenate((a,b,c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [55]:
np.concatenate((a,b,c),axis=None)

array([1, 2, 3, 4, 5, 6])

In [56]:
import numpy as np

x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [57]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [58]:
z=np.arange(20,24).reshape(2,2)
z

array([[20, 21],
       [22, 23]])

In [59]:
np.concatenate((x,y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [60]:
np.concatenate((x,y),axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [61]:
np.concatenate((x,y,z),axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [62]:
np.concatenate((x,y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

In [63]:
import numpy as ap

a= np.array([1,2,3])
a

array([1, 2, 3])

In [64]:
b= np.array([4,5,6])
b

array([4, 5, 6])

In [65]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
np.stack((a,b),axis=-1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
x=np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [70]:
y=np.arange(10,16).reshape(2,3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [71]:
z=np.arange(20,26).reshape(2,3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [72]:
ax0=np.stack((x,y,z),axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [73]:
ax0.shape

(3, 2, 3)

In [74]:
ax2=np.stack((x,y,z),axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [75]:
ax0.shape

(3, 2, 3)

In [76]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
x[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [79]:
np.expand_dims(x,axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [80]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [81]:
y[:,:,np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [82]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [83]:
np.expand_dims(z,axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [84]:
np.stack((x,y,z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])